title: Unip Warehouse
payoff: Believe in Design
email: hello@unipwarehouse.com
description: >
  I'm Hanif, a freelance Javanese illustrator and graphic designer<br>
  Based in Pati, Central Java.
baseurl: "/alpha"
url: "http://www.unipwarehouse.com"
logo: "/img/logo-horizontal.svg"
logo_small: "/img/logo-icon.svg"

# Build settings
markdown: kramdown

exclude:
  - resource
  - Gemfile
  - Gemfile.lock

# Collections
collections:
  posts:
    permalink: /posts/:categories/:title
  works:
    defaults:
      type: work
      layout: work
    permalink: /works/:categories/:title
    output: true

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      type: "post"
  -
    scope:
      type: "works"
    values:
      layout: "work"
      type: "work"

sass:
  style: compressed